Rename donor list to Hall of Fame
wmde/FundraisingFrontend pull request #2124
Opened 2021-02-26 08:55 UTC by Abban

https://phabricator.wikimedia.org/T274763

2021-03-02 09:28 UTC, gbirke approved these changes

2021-03-02 09:28 UTC, gbirke commented on config/routes.yaml
> +
Please add a comment that this is temporary and needs to be removed when manitu has adapted the web sever config to do the redirect

We don't want the framework to do stuff a web server/load balancer can do more efficiently.

2021-03-02 09:39 UTC, gbirke requested changes
For some reason, the composer update did not yet pick up the latest change to fundraising-frontend-content, leading to a 404 error when I tried it out. Updating the dependencies again made it work.

2021-03-09 16:28 UTC, moiikana commented
when I just tested locally I also needed to run `make update-php`, else it leads to 404 and is still at "Unterstützerliste".
current state also deployed to here: testing02.wikimedia.customers.manitu.net

2021-03-09 18:06 UTC, gbirke commented
I have moved the JS-related changes to https://gitlab.com/fun-tech/fundraising-app-frontend/-/merge_requests/16 

Please remove them from this PR

2021-03-10 16:29 UTC, gbirke approved these changes

2021-03-11 10:33 UTC, merged